n = int(input("Please tell me your age: "))
print(f"You are currently {n} years old.")
print(f"In 10 years, you will be {n + 10} years old.")
print(f"In 20 years, you will be {n + 20} years old.")
print(f"In 30 years, you will be {n + 30} years old.")